### ISSUE TITLE
Referenced Responses with '../' not resolving correctly - I think

### ISSUE THREAD

**Issue by ClappTrap** [cdimascio/express-openapi-validator#527]
**Describe the bug**
I am not sure if this is a bug. But I  have a schema that has numerous includes: 

`index.yaml`
```yaml
....
 /v1/foo:
    $ref: './resources/foo/paths.yaml'
....
```

`paths.yaml `
```yaml
post:
...add the before
  requestBody:
    description: Details to create test
    content:
      application/json:
        schema:
          $ref: './models.yaml#/MyModel'
...add the rest
get:
...add the rest
```
`models.yaml`
```yaml
MyModel:
  allOf:
    - $ref: "#/Test"
    - type: object
       properties:
         test:
           type: string
```
Having multiple operations in a file appears to produce an error. (I am going to investigate further.)
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read property 'content' of undefined
    at SchemaPreprocessor.extractResponseSchemaNodes (/~/project/node_modules/express-openapi-validator/dist/middlewares/parsers/schema.preprocessor.js:306:25)
    at SchemaPreprocessor.gatherSchemaNodesFromPaths (/~/project/node_modules/express-openapi-validator/dist/middlewares/parsers/schema.preprocessor.js:97:49)
    at SchemaPreprocessor.preProcess (/~/project/node_modules/express-openapi-validator/dist/middlewares/parsers/schema.preprocessor.js:56:24)
    at /~/project/node_modules/express-openapi-validator/dist/openapi.validator.js:81:95
```

Nope I extended the paths file to have 3 operations and the error resurfaced. 
--- further update
It actually looks like the resolution of the $ref pointer in the responses is not working. 
When I logged it, 
```json
{
  "401": { "$ref": "#/paths/~1v1~1tests/get/responses/401" }
}
```

My schema 

```yaml
responses:
    401:
      $ref: "../responses.yaml#/responses/UnauthorizedError"
```

--- further update, I was able to continue developing by using `refParser: dereference`

**Comment by th3g3ntl3men** [comment]
Sorry I keep messing with stuff, and keep hitting this error, I thought I had fixed it.

**Comment by cdimascio** [comment]
No problem. Thanks for the issue. Any chance u can provide a canonical example the reproduces the issue? Alternatively, If u r able to share your source code with me with instructions to run it, I'm happy to look there as well.

**Comment by th3g3ntl3men** [comment]
Let me get you a in-depth schema. I will have time later this week.

**Comment by ClappTrap** [comment]
I was able to track this down in my schema to a single instance i can replicate. I should have a schema to you this weekend. I have not forgotten, just been slammed.

**Comment by cdimascio** [comment]
Fantastic, thanks

**Comment by ClappTrap** [comment]
@cdimascio here is a minimal schema that breaks by including. 

https://github.com/ClappTrap/express-validator-schema-error

**Comment by cdimascio** [comment]
@ClappTrap please give v4.12.4 a try. I believe this is now resolved

**Comment by ClappTrap** [comment]
@cdimascio I tried it with my real schema, and it is still throwing the same error. 

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
app_1       | TypeError: Cannot read property 'content' of undefined
app_1       |     at SchemaPreprocessor.extractResponseSchemaNodes (/app/node_modules/express-openapi-validator/dist/middlewares/parsers/schema.preprocessor.js:293:25)
app_1       |     at SchemaPreprocessor.gatherSchemaNodesFromPaths (/app/node_modules/express-openapi-validator/dist/middlewares/parsers/schema.preprocessor.js:86:49)
app_1       |     at SchemaPreprocessor.preProcess (/app/node_modules/express-openapi-validator/dist/middlewares/parsers/schema.preprocessor.js:45:24)
app_1       |     at /app/node_modules/express-openapi-validator/dist/openapi.validator.js:82:95
```

I will do some more testing this weekend to see if I can pinpoint the problem in my schema. If I can, I'll provide a simple schema.

**Comment by cdimascio** [comment]
@ClappTrap that line number doesn't seem to line up with what i'd expect in `v4.12.4`. i just installed to have a look at line `293` . i see it as`const schemas = [];`. This is 9 lines or so above the one referenced in the error message.

i want to make sure your actually using the latest version...

would you mind removing your `node_modules` directory, verifying that 4.12.4 is in your package.json dependencies, then reinstalling

after installing, please check node_modules/express-openapi-validator/package.json and ensure its at 4.12.4.

**Comment by ClappTrap** [comment]
@cdimascio you are right, I had something misconfigured. everything works. Appreciate it.

**Comment by ClappTrap** [comment]
@cdimascio sorry spoke too soon, I just ran a full suite of tests against my express instance and this cropped up in the latest.

```
TypeError: Cannot read property '0' of undefined
at Object.dereferenceParameter (/app/node_modules/express-openapi-validator/dist/middlewares/parsers/util.js:10:45)
 at /app/node_modules/express-openapi-validator/dist/middlewares/parsers/schema.parse.js:30:38
 at Array.forEach (<anonymous>)
at ParametersSchemaParser.parse (/app/node_modules/express-openapi-validator/dist/middlewares/parsers/schema.parse.js:29:20)
 at RequestValidator.buildMiddleware (/app/node_modules/express-openapi-validator/dist/middlewares/openapi.request.validator.js:47:41)
 at RequestValidator.validate (/app/node_modules/express-openapi-validator/dist/middlewares/openapi.request.validator.js:38:37)
at /app/node_modules/express-openapi-validator/dist/openapi.validator.js:223:53 
at /app/node_modules/express-openapi-validator/dist/openapi.validator.js:158:28 my error super
```

I will do some more testing to see if I can pinpoint the schema breaking it.

**Comment by cdimascio** [comment]
Sounds good. Let me know what u find. Hopefully we can get this resolved for u soon

**Comment by ClappTrap** [comment]
No worries!

**Comment by AgentGoldenPaw** [comment]
@cdimascio i completely spaced this. sorry. This weekend I will have time to pinpoint the issue. But should I open a new issue or just post here?

**Comment by drpym** [comment]
I checked and in the latest two bumps everything resolves correctly.
